src/compojure/api/meta.clj
test/compojure/api/core_integration_test.clj

Hi,
I found that we wanted to put a number of common headers in one defschema, but a :headers option similar to :body was missing.  We added this to one of our internal projects, so I thought I'd submit it back upstream to you.   Let me know if this looks good or you have comments.
Thanks

Add restructure-param :headers option

---

project.clj

`lein start-thingie` did not correctly display swagger docs when
swagger-ui was at old version.

Bump swagger-ui to 2.1.8-M1

---

src/compojure/api/core.clj
src/compojure/api/meta.clj
test/compojure/api/core_integration_test.clj

See https://github.com/metosin/compojure-api/issues/79 for original issue.
This commit wraps `context*` routes in `compojure.core/routes` instead of `do`. Previously, the `do` form was only returning the last route in the `context*`, instead of all routes. See the [new test](https://github.com/metosin/compojure-api/pull/80/files#diff-2ef72077fcceeec886a02410dbc2d583R685) in `core_integration_tests.clj`.

wrap context* routes in compojure.core/routes instead of do

---

CHANGELOG.md
README.md
examples/src/examples/domain.clj
examples/src/examples/thingie.clj
project.clj
src/compojure/api/common.clj
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
src/compojure/api/routes.clj
src/compojure/api/swagger.clj
test/compojure/api/core_integration_test.clj
test/compojure/api/swagger_ordering_test.clj
test/compojure/api/swagger_test.clj
test/compojure/api/sweet_test.clj
test/compojure/api/test_utils.clj

initial support for Swagger 2.0. Some small breaking changes, and some deprecations (writing to STDOUT how to redo 'em better). Existing apps should work oob with Swagger 2.0 but require the latest `ring-swagger-ui` which is 2.0 -complient.
list of all changes in the `CHANGELOG.md`. 
- better support for tags (top-level entries with desriptions)
- verify ordering (currently unorders endpoints, test disabled for this, with TODOs)

Swagger 2.0 -support

---

CHANGELOG.md
project.clj
src/compojure/api/swagger.clj
test/compojure/api/core_integration_test.clj

Respect the Vanilla Compojure route matching: if there are several swagger routes with identical path & method, take only the first. Cleanup.
Fixes #89

Invalid doc with multiple identical route with context star

---

src/compojure/api/core.clj
src/compojure/api/swagger.clj
test/compojure/api/sweet_test.clj

Defroutes* is accessed over a Var for better development productivity.

---

CHANGELOG.md
examples/src/examples/thingie.clj
project.clj
src/compojure/api/meta.clj
test/compojure/api/core_integration_test.clj

A Breaking Change to simplify the response handling. Smooth transition via helpful `IllegalArgumentException`.

Swagger2 responses

---

src/compojure/api/meta.clj

it's now possible to have different consumes/produces pr. route instead
only on api/context.
I'm currently working on extending compojure-api to work with Liberator.
When using liberator and compojure, your nomally define one route per liberator resource with the ANY macro, and the liberator key  :allowed-methods  [:get :put] restricts the http verbs. 
My current approach is a macro with the following parameters [path params liberator-resource swagger]
and compiles a GET* PUT* POST* based on the :allowed-methods in the liberator resource 
And then inject the right swagger keys into each form (eg. :body for PUT, POST, PATCH) and :produces  :consumes (not for GET) based on the liberator key :available-media-types. 
What I need to do right now is move the parsing* and schema validation of …

add consumes and produces keys, at http verb level

---

examples/src/examples/thingie.clj
src/compojure/api/meta.clj
test/compojure/api/sweet_test.clj

:form-params or :multipart-params are probably never used together with other content-types so this should make sense?

Set :consumes in :form-params and :multipart-params

---

CHANGELOG.md
README.md
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
test/compojure/api/coercion_test.clj
test/compojure/api/core_integration_test.clj
test/compojure/api/integration_test.clj
test/compojure/api/meta_test.clj
test/compojure/api/test_utils.clj

Instead of using statically selected `:json` or `:query` coercion, one can now customize the coercion process either with api-level option or route-level restructuring. Value for both is a function of type `ring-request->coercion-type->coercion-matcher`.

Coercion matchers rethought

---

CHANGELOG.md
src/compojure/api/exception.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
test/compojure/api/integration_test.clj
test/compojure/api/middleware_test.clj

We decided to drop support for old options completely. Options are validated in compile time so there shouldn't be surprising runtime problems.
The default exception handlers are now defined using `compojure.api.exception` namespace instead of `meta` or `middleware`. `coerce!` still throws `:ring.swagger.schema/validation` which we map to our type. This is probably temporary solution as `coerce!` will be moved to another project and when that is done we should probably revisit request validation exception throwing.
Supersedes #158 and #143

Exception refactoring

---

src/compojure/api/meta.clj
src/compojure/api/middleware.clj
test/compojure/api/integration_test.clj
test/compojure/api/middleware_test.clj

We want to handle also response validation errors self,
so that we can log and notice invalid server data also from server logs in production and development.

Allow api users to also define own handler for response validation errors

---

CHANGELOG.md
project.clj
src/compojure/api/exception.clj
src/compojure/api/impl/logging.clj
src/compojure/api/logging.clj
test/compojure/api/middleware_test.clj

Fix for #172 - uses clojure.tools.logging for standard error logging if it's installed. Tests with and without the c.t.l -dependency.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/metosin/compojure-api/176)

Clojure.tools.logging

---

project.clj
src/compojure/api/meta.clj
test/compojure/api/perf_test.clj

Instead of creating the `coercer` on every request, we cache those via `clojure.core/memoize`. There will be a cache entry for all `schema` & `matcher` -pairs. Measured latency via `api` decreases by up to 40% in the new criterium tests, depending on the Schema complexity.

Memoize schema coercion

---

CHANGELOG.md
project.clj
src/compojure/api/meta.clj
test/compojure/api/coercion_test.clj

Use bouded (FIFO, size 100) route-level coercion cache instead of a global one. Avoids memory-leaks when matchers are recreated on every request (missing the cache completely). Worst case is that there will be `(* 100 number-of-routes)` matchers in the cache => negligible memory footprint.

Coercion memoization fix

---

src/compojure/api/common.clj
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
src/compojure/api/swagger.clj
test/compojure/api/coercion_test.clj
test/compojure/api/swagger_test.clj

This PR corrects a number of small typographical errors and clarity issues in the doc strings. 
No changes to the actual code present. All tests passed.

Fix typos and clarity issues in doc-strings

---

CHANGELOG.md
src/compojure/api/api.clj
src/compojure/api/common.clj
src/compojure/api/routes.clj
src/compojure/api/swagger.clj
test/compojure/api/common_test.clj
test/compojure/api/integration_test.clj
test/compojure/api/routes_test.clj
test/compojure/api/swagger_test.clj
test/compojure/api/test_utils.clj

* don't check at route creation time
* optionally check at api-creation time
* remove the *fail-on-missing-route-info* dynamic var
```clj
(fact "handling invalid routes with api"
(let [invalid-routes (routes (constantly nil))]
(fact "by default, logs the exception"
(api invalid-routes) => truthy
(provided
(compojure.api.impl.logging/log! :warn irrelevant) => irrelevant :times 1))
(fact "ignoring invalid routes doesn't log"
(api {:api {:invalid-routes-fn nil}} invalid-routes) => truthy
(provided
(compojure.api.impl.logging/log! :warn irrelevant) => irrelevant :times 0))
(fact "throwing exceptions"
(api {:api {:invalid-routes-fn routes/fail-on-invalid-child-routes}} invalid-routes)) => throws))
```

Route-validation as an api-option

---

CHANGELOG.md
examples/src/examples/thingie.clj
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
src/compojure/api/sweet.clj
test/compojure/api/integration_test.clj
test/compojure/api/routes_test.clj

Should be quite clear except for where to put the middleware functions.
Now they reside in `compojure.api.middleware` namespace which makes sense per naming, but the namespace used to contain only middlewares. Perhaps `common` namespace would be good fit for these functions?
I wonder if we should remove `middleware` macro when breaking stuff, I don't think there is any use case for it?

Middleware fix

---

src/compojure/api/meta.clj
test/compojure/api/integration_test.clj

This should allow using local bindings for :responses and :return
restructuring metadata.
Fixes #207

Moves responses merging from macro expansion to run-time

---

src/compojure/api/meta.clj
test/compojure/api/coercion_test.clj

Fixes #210 but not sure if moving `pre-lets` outside of the route body will cause performance problems.
Ping @ikitommi

Coercion context

---

CHANGELOG.md
README.md
examples/src/examples/thingie.clj
src/compojure/api/api.clj
src/compojure/api/common.clj
src/compojure/api/meta.clj
src/compojure/api/swagger.clj
src/compojure/api/sweet.clj
test/compojure/api/common_test.clj
test/compojure/api/integration_test.clj
test/compojure/api/routes_test.clj
test/compojure/api/sweet_test.clj

* remove `swagger-docs` & `swagger-ui`, use `swagger-routes` instead
* enable swagger-definitions via api-options.
Simplest thing that works:
```clj
(defapi app
(swagger-routes)
(GET "/hello" []
:query-params [name :- String]
(ok {:message (str "hello, " name)})))
(defapi app
{:swagger {:ui "/", :spec "/swagger.json"}}
(GET "/hello" []
:query-params [name :- String]
(ok {:message (str "hello, " name)})))
```
these are all equal:
```clj
;;
;; Swagger-routes
;;
(defapi app
(swagger-routes
{:data {:info {:title "API"
:description "Compojure Api example"}
:tags [{:name "hello", :description "says hello in Finnish"}]}})
(context "/hello" []
:tags ["hello"]
(GET "/" []
:query-params [name :- String]
:summary "say hello"
(ok {:message (str "Terve, " name)}))))
;;
;; Api-options
;;
(defapi app …
```

Swagger routes

---

src/compojure/api/swagger.clj
test/compojure/api/swagger_test.clj

Teach swagger-routes to heed basePath for swagger-docs path
If {:data {:basePath "/app"}} is given, default to including it as a
prefix to swagger-ui :swagger-docs path. The basePath is already passed
to swagger-docs, so this makes the swagger-ui consistent with the
generated json.
The swagger-docs path can also now be completely overridden via:
{:options {:ui {:swagger-docs "/override.json"}}}

Swagger routes basepath

---

src/compojure/api/meta.clj
test/compojure/api/integration_test.clj

The purpose of this change is to give custom exception handlers access to the planned response when a response body can't be coerced to the correct output schema.
The specific use case I've got in mind is that when response coercion fails, I'd like to log the body that my controller code was trying to return - without this I only have access to the schema-failure error messages, which can be a little opaque. I was originally planning to return just the body here, but having the entire response structure seems like it could be helpful in some cases (maybe for looking at returned content-type headers etc).

Include response when throwing on failed coercion

---

CHANGELOG.md
project.clj
src/compojure/api/api.clj
src/compojure/api/core.clj
src/compojure/api/resource.clj
src/compojure/api/routes.clj
src/compojure/api/swagger.clj
src/compojure/api/validator.clj
test/compojure/api/integration_test.clj
test/compojure/api/perf_test.clj
test/compojure/api/resource_test.clj

* **BREAKING**: Move `compojure.api.swgger/validate` to `compojure.api.validator/validate`.
* **BREAKING**: If a `resource` doesn't define a handler for a given `request-method` or for top-level, nil is returned (instead of throwing exeption)
* **BREAKING** Resource-routing is done by `context`. Trying to return a `compojure.api.routing/Route` from an endpoint like `ANY` will throw descriptive (runtime-)exception.
```clj
(context "/hello" []
(resource
{:description "hello-resource"
:responses {200 {:schema {:message s/Str}}}
:post {:summary "post-hello"
:parameters {:body-params {:name s/Str}}
:handler (fnk [[:body-params name]]
(ok {:message (format "hello, %s!" name)}))}
:get {:summary "get-hello"
:parameters {:query-params {:name s/Str}}
:handler (fnk [[:query-params name]]
(ok …
```

Small fixes (1.1.0)

---

src/compojure/api/middleware.clj

When defining an `api` one is allowed to pass in a vector of formats the api supports.
At this point one may insert a custom format. A simple case might be a json format that also encodes a specific version:
```clojure
(def my-custom-format
(format-response/make-encoder json/generate-string "application/vnd.vendor.v1+json"))
{:format  {:formats [my-custom-format :edn :json]}
:swagger {...}]}}}
```
A format can be either a keyword form a supported set of formats or a custom format.
Custom formats are maps that contain various necessary values that can be used to produce a response string. The `:content-type` key is used to describe the custom format content type, usually in mime type format.
The content type of custom formats should be part of the generated swagger document under the …

Respect :content-type attribute of custom formats

---

examples/metrics-ring/README.md
examples/metrics-ring/project.clj
examples/metrics-ring/src/example/handler.clj

See http://metrics-clojure.readthedocs.io/en/latest/ for information on integration with graphing services, instrumentation of the JVM, or instrumentation of specific routes.

Add an example that shows exposing an endpoint for ring metrics.

---

src/compojure/api/core.clj

Thanks for providing this great library btw!
This commit swaps the metadata map and args vector on various macros so that the metadata is found, and the CIDER indent is applied as intended.

Fix metadata position on defmacro to activate CIDER indent style

---

CHANGELOG.md
src/compojure/api/coerce.clj
src/compojure/api/meta.clj
src/compojure/api/resource.clj
test/compojure/api/integration_test.clj
test/compojure/api/meta_test.clj

* Restructuring `:body` does not keywordize all keys,
* e.g. EDN & Transit keys are not transformed, JSON keys based on the JSON decoder settings (defaulting to `true`).

Don't keywordize :body keys

---

CHANGELOG.md
README.md
project.clj
src/compojure/api/middleware.clj
test/compojure/api/coercion_test.clj
test/compojure/api/integration_test.clj
test/compojure/api/test_utils.clj

replace implementation (not the contract) of default coercion. in `compojure.api.middleware`:
* remove `default-coercion-matchers`
* use `create-coercion` & `default-coercion-options` instead for more fine grained access, uses format information prodived by [Muuntaja](https://github.com/metosin/muuntaja#request) to get format-level coercion.
* **BREAKING** new default coercion rules:
| Format | Request | Response |
| --------|:-------:|:------------:|
| `application/json` | `json-coercion-matcher` | validate |
| `application/edn` | `json-coercion-matcher` | validate |
| `application/msgpack` | `json-coercion-matcher` | validate |
| `application/x-yaml` | `json-coercion-matcher` | validate |
| `application/transit+json` | validate | validate |
| `application/transit+msgpack` | validate | …

More configurable coercion

---

CHANGELOG.md
project.clj
src/compojure/api/middleware.clj
test/compojure/api/integration_test.clj

* class-based exception handling made easier, the `[:exceptions :handlers]` options also takes the exception class names as keys,
used if the `:type`-based matching doesn't find a suitable handler: first against the exception class then the exception cause class.
```clojure
(api
{:exceptions
{:handlers
{::ex/default (custom-exception-handler :custom-exception)
IllegalAccessException (custom-exception-handler :illegal)}}}
...)
```

Class-based exception dispatch

---

src/compojure/api/help.clj
src/compojure/api/meta.clj

WIP.
```clojure
(require '[compojure.api.help :refer [help]])
(help)
; ------------------------------------------------------------
; Usage:
; 
; (help)
; (help topic)
; (help topic subject)
; 
; Topics:
; 
; :restructuring
; 
; Topics & subjects:
; 
; :restructuring :query-params
; :restructuring :summary
(help :restructuring)
; ------------------------------------------------------------
; Topic:
; 
; :restructuring
; 
; Subjects:
; 
; :query-params
; 
; Restructures query-params with plumbing letk notation.
; 
; Example: read x and optionally y (defaulting to 1)
; from query parameters. Body of the endpoint sees the
; coerced values.
; 
; (GET "/ping"
;   :query-params [x :- Long, {y :- Long 1}]
;   (ok (+ x y)))
; 
; :summary
; 
; A short summary of what the operation does. For …
```

Initial implementation for inline help

---

src/compojure/api/meta.clj
test/compojure/api/help_test.clj

Wrong keys were being used as dispatch values for some `help-for` defmethods, so the help for those `restructure-param` methods was not available.
Adds a test to verify that each and every `restructure-param` methods has a corresponding `help-for` method.

Fix help-for for some restructure methods

---

src/compojure/api/core.clj
src/compojure/api/meta.clj
test/compojure/api/integration_test.clj

*Allow `nil` paths in routing
* also flatten's the call stack, removing 3 extra function call when running contexts. nice.

Allow nil paths

---

CHANGELOG.md
README.md
project.clj
src/compojure/api/async.clj
src/compojure/api/resource.clj
test/compojure/api/middleware_test.clj
test/compojure/api/resource_test.clj

related to #297
* **BREAKING**: `resource` separates 1-arity `:handler` and 3-arity `:async-handler`. Rules:
* if resource is called with 1-arity, `:handler` is used, sent via `compojure.response/render`
* if resource is called with 3-arity, `:async-handler` is used, with fallback to `:handler`.
* sent via `compojure.response/send` so [manifold](https://github.com/ztellman/manifold) `Deferred` and [core.async](https://github.com/clojure/core.async) `ManyToManyChannel` can be returned.
```clj
(require '[compojure.api.sweet :refer :all])
(require '[clojure.core.async :as a])
(require '[manifold.deferred :as d])
(resource
{:summary "async resource"
:get {:summary "normal ring async"
:async-handler (fn [request respond raise]
(future
(Thread/sleep 100)
(respond (ok {:hello "world"})))
nil)} …
```

Resource async handler

---

CHANGELOG.md
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/sweet.clj
test/compojure/api/routes_test.clj

To address <https://github.com/metosin/compojure-api/issues/300>, this patch introduces `dynamic-context` which works just like `context` before optimizations.

Implement dynamic-context

---

src/compojure/api/resource.clj
test/compojure/api/resource_test.clj
test/compojure/api/test_utils.clj

This is to address the remaining concerns in issue #297.
* explain `:handler` and `:async-handler` in the `resource` docstring
* run resource tests both in sync and async mode
* fix the bug found by running the tests

Docstring and tests for async resource

---

src/compojure/api/common.clj
src/compojure/api/meta.clj
test/compojure/api/common_test.clj

Eastwood gives errors from 1-arity merge:
```clj
src/test_eastwood/core.clj:1:1: suspicious-expression: merge called with 1 args. 
(merge map) always returns map.  Perhaps there are misplaced parentheses?
```
use optimised `merge-vector` instead, actually 10x faster for the default case:
```clj
(criterium.core/quick-bench
(common/merge-vector [{:a 1}]))
; Evaluation count : 84624984 in 6 samples of 14104164 calls.
; Execution time mean : 5.661312 ns
; Execution time std-deviation : 0.305832 ns
; Execution time lower quantile : 5.152271 ns ( 2.5%)
; Execution time upper quantile : 5.942857 ns (97.5%)
; Overhead used : 1.782284 ns
(criterium.core/quick-bench
(apply merge [{:a 1}]))
; Evaluation count : 8572680 in 6 samples of 1428780 calls.
; Execution time mean : 68.158156 ns
; Execution …
```

Use optimised merge for merging endpoint parameters

---

src/compojure/api/meta.clj
src/compojure/api/resource.clj
src/compojure/api/routes.clj
src/compojure/api/swagger.clj
test/compojure/api/routes_test.clj
test/compojure/api/sweet_test.clj
test/compojure/api/test_utils.clj

This is to help with the migration to 2.0.
Implementation details:
* Now Route's `info` field contains Swagger data. This is moved under `:public` in `info`.
* The no-doc metadata is moved to the top level of `info`
* `info` top-level now has `:compojure.api.meta/static-context? true` if the route is affected by the static context optimization.
This is related to #300.

Implement a function to list static contexts

---

docs/release-checklist.md

Here's my list of things that should be done every time we do a release. This list is not specific to compojure-api – it could be used for any Metosin open source project – but since compojure-api is our most popular project, it makes sense to me to pay extra attention to it.
For bigger releases, this could be used as a base for a longer checklist. E.g. for compojure-api 2.0.0, we want to make sure that the migration guide covers everything and that we've posted about the release on Reddit.

Release checklist for compojure-api

---

CHANGELOG.md

There is a type in the CHANGELOG.md:107L
instead of:
`[metosin/spec-tools "0.2.2" :exlusions [org.clojure/spec.alpha]]`
it should be:
`[metosin/spec-tools "0.2.2" :exclusions [org.clojure/spec.alpha]]`

s/:exlusions/:exclusions

---

CHANGELOG.md
README.md
project.clj
src/compojure/api/middleware.clj
test/compojure/api/integration_test.clj
test/compojure/api/sweet_test.clj

Dropping the second class formats YAML & Msgpack. Both libs are not fully tested, cause reflection warning and don't seem to be actively maintained. Guide how to add them back. If this is approved, https://github.com/metosin/compojure-api/wiki/Migration-Guide-to-2.0.0 should be updated too.

Drop direct support for YAML & Msgpack

---

CHANGELOG.md
project.clj
src/compojure/api/api.clj
src/compojure/api/impl/json.clj
src/compojure/api/middleware.clj
src/compojure/api/request.clj
src/compojure/api/routes.clj
src/compojure/api/validator.clj
test/compojure/api/coercion/schema_coercion_test.clj
test/compojure/api/coercion_test.clj
test/compojure/api/integration_test.clj
test/compojure/api/perf_test.clj
test/compojure/api/routes_test.clj
test/compojure/api/test_utils.clj
test19/compojure/api/coercion/spec_coercion_test.clj

Drop direct dependency to Cheshire in favour of Muuntaja, which is also injected into request for endpoints to use. Muuntaja uses Cheshire under the covers.

Drop cheshire

---

README.md

Minor - noticed these while pasting the examples into my editor.

Correct mismatched brackets in README examples.

---

src/compojure/api/methods.clj
src/compojure/api/resource.clj
src/compojure/api/routes.clj
test/compojure/api/routes_test.clj

This is necessary in order to appease Swagger (and probably other doc specs). At the moment `ANY` created a `nil` method and so a `nil` key is present in the path map. This results in an invalid Swagger doc.
e.g.
Old:
```clojure
=> (extract-paths (api (ANY "*" [] identity)))
#linked/map [["*" {nil {}}]]
```
New:
```clojure
=> (extract-paths (api (ANY "*" [] identity)))
#linked/map [["*" {:get {}, :patch {}, :delete {}, :head {}, :post {}, :options {}, :put {}}]]
```

`ANY` method now expands to all methods

---

src/compojure/api/meta.clj
test/compojure/api/integration_test.clj

- Catch the exception thrown in `fnk-schema` and rethrow it with link
to fnk-syntax

Give better error message when binding isn't valid. Fixes #354

---

src/compojure/api/middleware.clj

Hello!
I've been having issues with this and I'm proposing you this change to see what do you think.
Checking with `fn?` returns false for data structures implementing the `IFn` interface such as keywords or more importantly, multimethods. `ifn?` solves this and checks for any data structure implementing `IFn`.
Thanks!

Change check fn? by ifn?

---

src/compojure/api/coercion.clj
test/compojure/api/coercion_test.clj

When async handlers returned an invalid format, the previous
wrap-coerce-response would just time out instead of passing the
error.

Deal with coercion exceptions in async handlers

---

src/compojure/api/coercion/schema.clj
src/compojure/api/coercion/spec.clj

Removes the log call that is shown every time compojure coercion is enabled.
The logging is unnecessary and unexpected because it shows every time the schema/spec coercion namespace is required.

Remove logging that tells when coercion is enabled

---

project.clj

* Added `:pendatic? :abort`.
* Revised conflict resolution: instead of using `:exclusions` I explicitly "pinned" libs causing conflicts at the very top of the deps list in the new section `; Fix conflicts`.
* Couldn't delete exclusions from `[manifold "0.1.8" :exclusions [org.clojure/tools.logging]]` because then tests fail in peculiar way:
<details>
<summary>Click to expand</summary>
```
ᐅ lein do clean, all midje
Tried to load commons-io version 2.5 but 2.6 was already loaded.
Tried to load com.google.guava/guava version 19.0 but 20.0 was already loaded.
Performing task 'midje' with profile(s): 'dev'
WARNING: any? already refers to: #'clojure.core/any? in namespace: leiningen.midje, being replaced by: #'leiningen.midje/any?
WARN clojure.tools.logging not found on classpath, …
```

Add `pedantic? :abort`, fix dep conflicts (#415)

---

project.clj

This lib:  [(https://github.com/clj-commons/ordered)] has undergone changes, causando alguns problemas em outras bibliotecas que dependiam delas como a clj-yaml. The lib of clj-yml is used in ring-middleware-format. All have already been updated.  Only this version of compojure-api not yet. This change addresses this issue.

update version because problens in clj-commons/ordered

---

.travis.yml
CHANGELOG.md
project.clj
test/compojure/api/integration_test.clj

I'm going to create a maintenance release in the 1.1.x series with the aim of supporting new versions of Java.

1.1.x: Dependency maintenance

---

src/compojure/api/coercion.clj
src/compojure/api/coercion/spec.clj

Schema coercion allows `:responses {200 {}}` but spec coercion doesn't. This patch changes spec coercion to allow it as well.
Fixes #413.

Fix empty spec response coercion to mirror schema
