CHANGELOG.md
examples/src/examples/thingie.clj
project.clj
src/compojure/api/common.clj
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/swagger.clj
src/compojure/api/sweet.clj
test/compojure/api/common_test.clj
test/compojure/api/core_integration_test.clj
test/compojure/api/meta_test.clj
test/compojure/api/swagger_test.clj
test/compojure/api/sweet_test.clj

Context star clear

---

CHANGELOG.md
examples/src/examples/thingie.clj
src/compojure/api/meta.clj
src/compojure/api/upload.clj

Requires https://github.com/metosin/ring-swagger/pull/44
Low-level stuff needed for File uploads.

Fixes #74. Support :consumes, :produces and :multipart-params restructuring

---

CHANGELOG.md
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
src/compojure/api/routes.clj
src/compojure/api/swagger.clj
src/compojure/api/sweet.clj
test/compojure/api/core_integration_test.clj
test/compojure/api/swagger_test.clj
test/compojure/api/sweet_test.clj

Path for fix

---

CHANGELOG.md
examples/dev-src/user.clj
examples/src/examples/server.clj
examples/src/examples/thingie.clj
project.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj

I guess this could use a bit more documentation but other than that this should be good.

Component integration

---

src/compojure/api/core.clj
test/compojure/api/integration_test.clj

Api route compilation stack overflow error

---

src/compojure/api/core.clj

Super minor issue, but why not fix it? :)

Fix typo in docstring: Was missing the closing ]

---

CHANGELOG.md
project.clj
src/compojure/api/exception.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
test/compojure/api/middleware_test.clj

Supersedes #195
Changes the implementation a bit but all changes are now breaking.

Exception logging 2

---

CHANGELOG.md
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/middleware.clj
test/compojure/api/coercion_test.clj
test/compojure/api/compojure_perf_test.clj
test/compojure/api/routes_test.clj

Performance

---

CHANGELOG.md
src/compojure/api/middleware.clj
test/compojure/api/integration_test.clj

Handle exception superclasses, not nesteds

---

CHANGELOG.md
project.clj
src/compojure/api/swagger.clj
test/compojure/api/swagger_test.clj

changes for https://github.com/metosin/ring-swagger/pull/118

Use the new (async-ring supported) swagger-ui routes

---

examples/async/src/example/handler.clj

Change result type of async divide example to Float

---

src/compojure/api/core.clj
src/compojure/api/meta.clj

Compojure 1.6 includes the fixed functions: https://github.com/weavejester/compojure/commit/0920456a659c317c8b2dae19038f4987a46e8d30

Remove copied Compojure code

---

CHANGELOG.md
project.clj
src/compojure/api/resource.clj
test/compojure/api/resource_test.clj

* Add support for `:middleware` for resources to make them more composable
* Merge `resource` options & info
* Update deps

Resource middleware

---

CHANGELOG.md
project.clj
src/compojure/api/api.clj
src/compojure/api/coerce.clj
src/compojure/api/core.clj
src/compojure/api/exception.clj
src/compojure/api/meta.clj
src/compojure/api/resource.clj
src/compojure/api/routes.clj
test/compojure/api/coercion_test.clj
test/compojure/api/exception_test.clj
test/compojure/api/help_test.clj
test/compojure/api/integration_test.clj

Fixes #304 & #306.
```clj
(let [app (GET "/" []
:return {:x String}
(ok {:kikka 2}))]
(try
(app {:request-method :get, :uri "/"})
(catch Exception e
(ex-data e))))
; {:type :compojure.api.exception/response-validation,
;  :validation :schema,
;  :in [:response :body],
;  :schema {:x java.lang.String},
;  :errors {:x missing-required-key, 
;           :kikka disallowed-key},
;  :response {:status 200,
;             :headers {}, 
;             :body {:kikka 2}}}
(let [app (GET "/" []
:query-params [x :- String]
(ok))]
(try
(app {:request-method :get, :uri "/" :query-params {:x 1}})
(catch Exception e
(ex-data e))))
; {:type :compojure.api.exception/request-validation,
;  :validation :schema,
;  :value {:x 1},
;  :in [:request :query-params],
;  :schema {Keyword Any, :x java.lang.String},
; …
```

More descriptive error messages

---

src/compojure/api/async.clj

I'm going to remove muuntaja.util/when-ns from Muuntaja, so let's put it here.

Inline muuntaja.util/when-ns

---

CHANGELOG.md
project.clj
src/compojure/api/core.clj
src/compojure/api/meta.clj
src/compojure/api/sweet.clj
test/compojure/api/integration_test.clj
test/compojure/api/routes_test.clj

* Support `sequential?` routes
* Update deps
* drop `dynamic-context` in favour of `:dynamic` meta (less syntax, more meta)
Fixes #348

Small fixes part x

---

src/compojure/api/coercion/spec.clj

- Extract function to stringify the pred part of the problem-statment
- Realize the pred if it's a lazy-seq

Realize lazy-seq to make better error message. Fixes #355

---

CHANGELOG.md
project.clj
src/compojure/api/meta.clj
test19/compojure/api/coercion/spec_coercion_test.clj

Make `:coercion` work with contexts. Context handling is starting to be non-trivial....

Fix context+coercion

---

README.md
src/compojure/api/validator.clj

After using c-api for the first time, there were few points I was not sure how to do it. Or I found examples deep inside repository but thought I would have saved some times if the examples were in the README. This PR aims to address those problems that library first time users might encounter.
Thank you metosin for making awesome libraries like this one.

Doc improve

---

CHANGELOG.md
src/compojure/api/api.clj
src/compojure/api/middleware.clj
test/compojure/api/integration_test.clj

welcome wrap-format!

---

src/compojure/api/coercion/spec.clj
test19/compojure/api/coercion/spec_coercion_explain_test.clj
test19/compojure/api/coercion/spec_coercion_test.clj

Fixes #409 
I'm not familiar with midje, let me know if the tests aren't good enough.

Use coerced value when calling explain-data

---

project.clj

This also fixes https://github.com/metosin/compojure-api/issues/438

update metosin/ring-swagger-ui to 3.24.3
